version: '3'

services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
    volumes:
      - .:/app
    entrypoint: bash ./entrypoint.sh
    networks:
      - goexpert-clean-arch-rafaelpapastamatiou

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "--execute", "SHOW DATABASES;"]
      start_interval: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - goexpert-clean-arch-rafaelpapastamatiou

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - goexpert-clean-arch-rafaelpapastamatiou

networks:
  goexpert-clean-arch-rafaelpapastamatiou: